snoop:
   applicationName: snoopydemo
   applicationHome: http://localhost:8080/snoopy-demo/
#   serviceUrl: ws://localhost:8080/snoop-service/
   serviceUrl: ws://192.168.59.103:8081/snoop-service/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  